Created design for the join game page
dapopovic/SE2_Anti-Monopoly pull request #18
Opened 2024-04-07 21:32 UTC by JulieL999

2024-04-08 11:13 UTC, dapopovic commented
join game class does not exist

2024-04-08 17:49 UTC, dapopovic commented on Client/app/src/main/AndroidManifest.xml
> +            android:exported="true"
this should be false

2024-04-10 13:27 UTC, Ragnarus reviewed
You could merge it

2024-04-16 11:52 UTC, dapopovic requested changes

2024-04-16 11:52 UTC, dapopovic commented on Server/src/test/java/at/aau/anti_mon/server/websocket/WebSocketHandlerClientImpl.java
> +                    case ANSWER -> {
Case Pin is missing

2024-04-18 08:47 UTC, merged